# Name of the Workflow
name: code

# When the workflow should run
on: 
  push:

# Jobs in the workflow
jobs:
  code-checkout:
    runs-on: ubuntu-latest

# Steps in the workflow
    steps:
      - name: Clone the code
        uses: actions/checkout@v7
    
      - name: Print the message
        run: echo "Code Cloned"
